# Generated by Django 4.2.6 on 2024-05-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
